<<<<<<< Updated upstream
# Generated by Django 4.2.25 on 2026-03-15 22:02
=======
# Generated by Django 5.2.7 on 2026-03-15 22:36
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
