# Generated by Django 6.0 on 2026-03-15 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='demandeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='parent_ticket',
            field=models.ForeignKey(blank=True, limit_choices_to={'ticket_type': 'story'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='blog.ticket', verbose_name='User Story parente'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('story', 'User Story'), ('task', 'Task'), ('bug', 'Bug')], default='story', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='workload_done',
            field=models.PositiveIntegerField(default=0, verbose_name='Charge effectuée'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='workload_initial',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Charge initiale'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='workload_remaining',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Charge restante'),
        ),
    ]
