# Generated by Django 5.2.11 on 2026-03-18 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_ticket_assignee_alter_ticket_demandeur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
