# Generated by Django 5.2.7 on 2026-03-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_sprint_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='assignee',
            new_name='assigned',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='demandeur',
            new_name='requester',
        ),
    ]
