# Generated by Django 6.0 on 2026-03-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_sprint_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
