# Generated by Django 4.2.25 on 2026-03-30 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_epic_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='parent_ticket',
            field=models.ForeignKey(blank=True, limit_choices_to={'ticket_type': 'story'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='blog.ticket', verbose_name='Linked to'),
        ),
    ]
