# Generated by Django 5.2.7 on 2026-03-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_epic_priority'),
        ('blog', '0005_rename_assignee_ticket_assigned_and_more'),
    ]

    operations = [
    ]
