# Generated by Django 4.2.25 on 2026-04-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_ticket_parent_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('contributor', 'Contributor'), ('readonly', 'Read-Only')], default='contributor', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
    ]
