# Generated by Django 4.2.25 on 2026-04-08 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_alter_announcement_project_sprintmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='blog.project'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Urgent'), ('success', 'Success')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to'),
        ),
    ]
